name: "Lint Golang files"

on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  golangci:
    name: "Run golang CI linter"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ stable ]
        os: [ ubuntu-latest-amd64, ubuntu-latest-arm64 ]
    steps:
    - uses: actions/checkout@v6.0.1
    - uses: actions/setup-go@v6.1.0
      with:
        go-version: ${{ matrix.go }}
    - uses: golangci/golangci-lint-action@v9.1.0
      with:
        version: v2.6.2 # renovate: datasource=github-releases depName=golangci/golangci-lint
