name: "Lint Markdown files"

on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]
  workflow_dispatch: {}

jobs:
  markdown-lint:
    name: "Run markdown linter"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: DavidAnson/markdownlint-cli2-action@30a0e04f1870d58f8d717450cc6134995f993c63 # v21.0.0
      with:
        globs: '**/*.md'
