name: Markdown linter

on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]
  workflow_dispatch: {}

jobs:
  markdown-lint:
    container:
      image: git.cryptic.systems/volker.raschek/markdownlint:0.45.0
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Lint Markdown files
      run: markdownlint --config .markdownlint.yaml .