name: "Release"

on:
  push:
    tags: [ '**' ]

permissions:
  contents: write

jobs:
  release:
    name: "Release application"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      with:
        image: harbor.cryptic.systems/docker/tonistiigi/binfmt:latest
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: stable
    - uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
      with:
        registry: git.cryptic.systems
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_CRYPTIC_SYSTEMS_PACKAGE_REGISTRY_TOKEN }}
    - env:
        GITEA_TOKEN: ${{ secrets.GIT_CRYPTIC_SYSTEMS_PACKAGE_REGISTRY_TOKEN }}
        GONOSUMDB: ${{ vars.GONOSUMDB }}
        GOPROXY: ${{ vars.GOPROXY }}
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        version: v2.16.0 # renovate: datasource=github-releases depName=goreleaser/goreleaser
        args: release --clean

  sync-to-hub-docker-io:
    name: "Upload Images to docker.io"
    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - name: Copy images to docker.io
      run: |
        TAG=$(echo ${{ github.ref_name }} | sed 's/v//gm')

        apt-get update --yes
        apt-get install --yes skopeo
        skopeo copy \
          --all \
          --dest-password ${{ secrets.DOCKER_IO_PASSWORD }} \
          --dest-username ${{ secrets.DOCKER_IO_USERNAME }} \
          --src-password ${{ secrets.GIT_CRYPTIC_SYSTEMS_PACKAGE_REGISTRY_TOKEN }} \
          --src-username volker.raschek \
            docker://git.cryptic.systems/volker.raschek/tarr:${TAG} \
            docker://docker.io/volkerraschek/tarr:${TAG}
